/**
 * Combined Drizzle schema for migrations and the app DB client.
 * Auth tables are generated by Better Auth — do not hand-edit auth-schema.ts.
 */
export * from "./auth-schema"
export {
  budget,
  budgetMembership,
  budgetRelations,
  BUDGET_MEMBERSHIP_ROLES,
  BUDGET_STATUSES,
  type BudgetMembershipRole,
  type BudgetStatus,
} from "@/features/budgets/db/schema"
